# Generated by Django 5.0.6 on 2024-07-02 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favouritestories',
            old_name='firebase_story_id',
            new_name='story_id',
        ),
    ]
